modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/maximilian1121/Helpful-Huds/issues"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Maximilian"
description = '''
${description}
'''
logoFile = "assets/${id}/icon.png"
logoBlur = false

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"
